[package]
name = "offregisters-ctl"
version = "0.0.1"
authors = ["Samuel Marks <samuel@offscale.io>", "Swoorup Joshi <swoorupj@gmail.com"]
edition = "2018"

[dependencies]
offregisters-lib = { path = "../offregisters-lib" }
structopt = "0.2"
serde_yaml = "0.8"