---
name: taiga
version: 0.0.1-alpha
depends:
  - exec: echo 
    args:
      -  hello 
      -  world
    env:
      RUST: 123
  - exec: sleep 
    args: 
      - 1
env: 
    RUST_BACKTRACE: 1
pipe: 
    exec: cat